language: python
python: 
<<<<<<< HEAD
	- "2.7"
addons:
  sauce_connect:
    username: automation_runner
    access_key:
      secure: "PPPG+8TxGxjd98aA2/EEULap2YP/l//CsWfIiTUhTcbJs6tvlpyeF5t6K8Yqso8uowVoY41q5ID3iXUZksHTfxnGhaKKLwCFolnKcOF5QNtFHm9bA8Zzc91OyeUSdtHYytHHzdxxfAyxq2KPTAbA/U0yZ/rh6ZIZ3xTCjfQQE9U="


=======
  - "2.7"
env:
   global:
     - secure: "ASHu9YNhvAbQWlE+fPS2fjJM/l34PElMG14vGj/KkDGf28p6V92fiC+SjQTYwbzBFeWF+pwnDI45+X6iqRnI0zLZdIxuOwXhKkIOb1A+CfsU6wOZ0AgtCOUGSdJbzK8QWzS+38M3j15dgM5yFI4EbTG4Q0jvZcXjMwnVZ047DX0="
     - secure: "N53oL1tapmnJCsHDoXKcJfQz2c9ThYYNcbxMh5CgP/bOsP7XQvjH7HXQOrN1IgSRFnTNe0qgM5ifrVptc4zOEVEzUgCmFEvGIbXwwbIvs5Mp0+h4+k6eX3+dkMsF+hnp1P5CjoAGLrPHOGTH7iFmVqBoQE5ktHVDp7A6uoCudtQ="
>>>>>>> 784fcf21a2be7ba1b1a27280cbed9c03be425ceb
install: 
  - pip install selenium nose --use-mirrors
script: 
  - nosetests -v

